name: SpeccerServer
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: derek <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: '^1.0.0'
  test: '^1.0.0'
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
  postgres: '^1.0.2'
  uuid: '>=0.0.0'
  dbcrypt: '>=0.0.0'
